---

- hosts: all
  become: true

  tasks:
    - name: Create project directory
      file:
       path: /var/www/bewamo
       state: directory
       mode: 0775

    - name: Checkout project
      git:
        dest: /tmp/bewamo
        repo: https://github.com/momokeith/bewamo.git
        version: develop

    - name: Get last commit hash
      command: git rev-parse HEAD
      args:
        chdir: /tmp/bewamo
      register: commit_hash

    - debug:
        msg: "Deploying {{ commit_hash.stdout }}"

    - name: Moving from tmp
      command: mv /tmp/bewamo /var/www/bewamo/{{ commit_hash.stdout }}

    - name: Running composer
      command: composer install
      args:
        chdir: /var/www/bewamo/{{ commit_hash.stdout }}

    - name: Running tests
      command: bin/phpspec r
      args:
        chdir: /var/www/bewamo/{{ commit_hash.stdout }}

    - name: Change directory access
      file:
       path: /var/www/bewamo/{{ commit_hash.stdout }}
       state: touch
       mode: "u+rwx,g-wx,o-rwx"
       owner: www-data
       group: www-data

    - name: Create link
      file:
       path: /var/www/bewamo/current
       src: /var/www/bewamo/{{ commit_hash.stdout }}
       state: link
       mode: 0755