---

- hosts: all
  become: true

  tasks:
    - name: Create project directory
      file:
       path: /var/www/bewamo
       state: directory
       mode: 0755

    - name: Checkout project
      git:
        dest: /tmp/bewamo
        repo: https://github.com/momokeith/bewamo.git
        version: develop

    - name: Get last commit hash
      command: git rev-parse HEAD
      args:
        chdir: /tmp/bewamo
      register: commit_hash

    - name: Deploying
      command: mv /tmp/bewamo /var/www/bewamo/{{ commit_hash.stdout }}

    - name: Create link
      file:
       path: /var/www/bewamo/current
       src: /var/www/bewamo/{{ commit_hash.stdout }}
       state: link
       mode: 0755
