---

- hosts: all
  become: true

  tasks:
    - name: Create project directory
      file:
       path: /var/www/bewamo
       state: directory
       mode: 0755

    - name: Checkout project
      git:
        dest: /var/www/bewamo/12345
        repo: https://github.com/momokeith/bewamo.git
        version: develop

    - name: Create link
      file:
       path: /var/www/bewamo/current
       src: /var/www/bewamo/12345
       state: link
       mode: 0755
